export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { ThemeProviderComponent } from "../contexts/ThemeContext";
import { Paper } from "@mui/material";
import "../styles/globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProviderComponent>
        <body>
          <Paper sx={{ m: 0, pt: 4 }}>{children} </Paper>
        </body>
      </ThemeProviderComponent>
    </html>
  );
}
